---
# Delegate installation server
hashivault__delegate_to: vault

# Installation dependencies
hashivault__base_packages:
  - unzip

# Configuration paths
hashivault__tmp_dir: /tmp/hashivault_role
hashivault__install_dir: /opt/vault
hashivault__config_dir: /etc/vault.d

# Version app
hashivault__version: 1.12.1

# User and group in server installation
hashivault__user: vault
hashivault__group: vault

# Name in FQDN
hashivault__server_fqdn: vault.example.local

# Shares and Threshold to unseal
hashivault__init_key_shares: 5
hashivault__init_key_threshold: 3
