---
- name: "Installation of Hashicorp Vault"
  hosts: vault
  gather_facts: true

  tasks:
  roles:
    - hashivault
  vars:
    hashivault__version: 1.12.1
    hashivault__server_fqdn: vault.example.local
