---
galaxy_info:
  role_name: hashivault
  author: Fernando Hernandez San Felipe
  description: Role for deploy and install Hashicorp Vault server
  company: Orphenix IT
  issue_tracker_url: https://github.com/ironwolphern/hashivault-role/issues
  license: license MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all

  galaxy_tags:
    - hashicorp
    - vault
    - security
    - secrets
    - system

dependencies: []
