---
- name: "Backup Hashicorp Vault server | backup | {{ _title_pfx }}"
  delegate_to: "{{ hashivault__delegate_to }}"
  become: true
  tags: backup
  block:

    - name: "Header | install | {{ _title_pfx }}"
      ansible.builtin.debug:
        msg: "----------------------------------- BACKUP / AUTO ------------------------------------"
      tags: auto

    - name: "Backup Hashicorp Vault server automatic | backup | {{ _title_pfx }}"
      ansible.builtin.cron:
        name: "Backup Hashicorp Vault server automatic"
        minute: "{{ hashivault__backup_minute }}"
        hour: "{{ hashivault__backup_hour }}"
        weekday: "{{ hashivault__backup_weekday }}"
        user: root
        job: |
          "vault operator raft snapshot save {{ hashivault__install_dir }}/backup/{{ hashivault__snap_name }}_{{ ansible_date_time.iso8601_basic_short }}.snap"
        cron_file: hashivault_backup
      tags: auto

    - name: "Rotate backup files Hashicorp Vault server | backup | {{ _title_pfx }}"
      ansible.builtin.cron:
        name: "Rotate backup files Hashicorp Vault server"
        minute: "{{ hashivault__backup_rotate_minute }}"
        hour: "{{ hashivault__backup_rotate_hour }}"
        weekday: "{{ hashivault__backup_rotate_weekday }}"
        user: root
        job: "find {{ hashivault__install_dir }}/backup -type f -name '{{ hashivault__snap_name }}_*.snap' -mtime +{{ hashivault__backup_rotate }} -delete"
        cron_file: hashivault_backup_rotate
      when: hashivault__backup_rotate > 0
      tags: auto

    - name: "Header | install | {{ _title_pfx }}"
      ansible.builtin.debug:
        msg: "----------------------------------- BACKUP / MANUAL ----------------------------------"
      tags: manual

    - name: "Backup Hashicorp Vault server manual | backup | {{ _title_pfx }}"
      ansible.builtin.command:
        cmd: vault operator raft snapshot save "{{ hashivault__install_dir }}/backup/{{ hashivault__snap_name }}.snap"
      register: _hashivault_backup
      changed_when: _hashivault_backup.rc == 0
      tags: manual
