---
- name: "Post-install Hashicorp Vault server | post_install | {{ _title_pfx }}"
  delegate_to: "{{ hashivault__delegate_to }}"
  become: true
  tags: post_install
  block:

    - name: "Header | post_install | {{ _title_pfx }}"
      ansible.builtin.debug:
        msg: "------------------------------------ POST_INSTALL ------------------------------------"

    - name: "Login to Hashicorp Vault server | post_install | {{ _title_pfx }}"
      ansible.builtin.command:
        cmd: "vault login {{ _hashivault__init_parsed_vault.root_token }}"
      environment:
        VAULT_ADDR: "https://{{ hashivault__server_fqdn }}:8200"
      register: _hashivault__login
      changed_when: _hashivault__login.rc == 0
      run_once: true
      no_log: true

    - name: "Enable Hashicorp Vault server audit device | post_install | {{ _title_pfx }}"
      ansible.builtin.command:
        cmd: "vault audit enable -local file file_path={{ hashivault__install_dir }}/log/vault_audit.log"
      environment:
        VAULT_ADDR: "https://{{ hashivault__server_fqdn }}:8200"
      register: _hashivault__audit_enable
      changed_when: _hashivault__audit_enable.rc == 0
      run_once: true
